spring:
  h2:
    console:
      enabled: true
      path: /consulta/h2
      
  datasource:
    url: jdbc:h2:mem:consulta
  application:
    name: consulta

server:
  port: 8083  
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
      