spring:
  application:
    name: gateway
    
  cloud:
    gateway:
      routes:
      - id: medicos
        uri: lb://medicos
        predicates:
            - Path=/medicos/**
      - id: pacientes
        uri: lb://pacientes
        predicates:
            - Path=/pacientes/**
      - id: consultas
        uri: lb://consultas
        predicates:
            - Path=/consultas/**
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8989 
          