spring:
  h2:
    console:
      enabled: true
      path: /medico/h2
      
  datasource:
    url: jdbc:h2:mem:medicos
  application:
    name: medicos

server:
  port: 8082  
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
      